//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmersMarketsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class market
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public market()
        {
            this.markets_categories = new HashSet<markets_categories>();
            this.reviews = new HashSet<review>();
        }
    
        public int market_id { get; set; }
        public string market_name { get; set; }
        public string street { get; set; }
        public Nullable<int> city { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<int> zip { get; set; }
        public Nullable<float> lat { get; set; }
        public Nullable<float> lon { get; set; }
    
        public virtual city city1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<markets_categories> markets_categories { get; set; }
        public virtual state state1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<review> reviews { get; set; }
    }
}
