//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmersMarketsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class review
    {
        public int review_id { get; set; }
        public int user_id { get; set; }
        public int market_id { get; set; }
        public System.DateTime date_time { get; set; }
        public short score { get; set; }
        public string review1 { get; set; }
    
        public virtual market market { get; set; }
        public virtual user user { get; set; }
    }
}
